[package]
name = "ark-segmentlookup"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.3.0"
ark-poly = "0.3.0"
ark-ec = "0.3.0"
ark-std = "0.3.0"
fk = { git = "https://github.com/geometryresearch/fk", rev = "91143a8" }
sha3 = "0.10.6"
ark-serialize = { version = "^0.3.0", default-features = false, features = ["derive"] }
merlin = { version = "3.0.0" }

[dev-dependencies]
ark-bn254 = "0.3.0"
rand_chacha = { version = "0.3.0", default-features = false }
