[package]
name = "e2e-test"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = { version = "0.4.0", features = ["parallel"] }
ark-ec = { version = "0.4.2", features = ["parallel"] }
ark-bn254 = "0.4.0"
ark-segmentlookup = { path = "../.." }